<?php

namespace Polymer\Tests\Entity\Repositories;

use Polymer\Repository\Repository;

/**
 * CompanyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyRepository extends Repository
{
}
